Pp task1 1 3
AnnaLillOrganisation/Task1.1.3 pull request #1
Opened 2024-01-22 02:46 UTC by AnnaLill

2024-01-22 07:41 UTC, pdasilem requested changes

2024-01-22 07:41 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/Main.java
> +    private final static UserService userService = new UserServiceImpl();
избавься от статики

2024-01-22 07:41 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +    private static final Connection connection = Util.getConnection();
инициализация в каждом методе конекшна

2024-01-22 07:41 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +        try (PreparedStatement pstm = connection.prepareStatement("INSERT INTO users (name, last_name, age) VALUES (?, ?, ?)")) {
пстм слишком... грубо.
кодстайл - по названию класса/интерфейса в кэмелкейс

2024-01-22 07:41 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/util/Connection.java
> +public class Connection {
этот класс зачем?

2024-01-22 13:14 UTC, AnnaLill commented on src/main/java/jm/task/core/jdbc/util/Connection.java
> +public class Connection {
не понимаю почему, но пока не создала этот класс, коннекшн не работал при написании реализации кода соединения к бд, сейчас удалила класс, все работает

2024-01-22 13:14 UTC, AnnaLill commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +        try (PreparedStatement pstm = connection.prepareStatement("INSERT INTO users (name, last_name, age) VALUES (?, ?, ?)")) {
исправила

2024-01-22 13:14 UTC, AnnaLill commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +    private static final Connection connection = Util.getConnection();
сделала

2024-01-22 13:14 UTC, AnnaLill commented on src/main/java/jm/task/core/jdbc/Main.java
> +    private final static UserService userService = new UserServiceImpl();
избавилась

2024-01-23 09:55 UTC, pdasilem approved these changes

2024-01-29 11:35 UTC, merged